eventos/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('ver-evento/<pk>/', views.ver_evento.as_view(), name='ver-evento'),
    path('eliminar-evento/<int:id>/', views.eliminar_eventos, name='eliminar-evento'),
    path('crear-evento/', views.crear_evento, name="crear-evento"),
    path('guardar-evento/', views.guardar_evento, name="guardar-evento"),
]

login/urls.py
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registro/', views.registro, name='registro'),
    path('accounts/', include('allauth.urls')),
]

reservasRestaurante/urls.py
from django.contrib import admin
from django.urls import path, include
# from reservas import views as reservas_view


urlpatterns = [
    path('', include('reservas.urls')),
    path('', include('login.urls')),
    path('', include('productos.urls')),
    path('', include('eventos.urls')),
    path('', include('perfil.urls')),
    path('', include('contactos.urls')),
    path('', include('usuarios.urls')),
    path('', include('tareas.urls')),


    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    ]

eventos/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Evento(models.Model):

    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30)
    imagen = models.ImageField(upload_to=None, height_field=None, width_field=None, max_length=100, null=True)
    descripcion = models.TextField(max_length=1000, null = True)

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.titulo

    def __unicode__(self,):

        return str(self.imagen)

eventos/views.py
from django.shortcuts import redirect, render
from .models import *
from django.views import generic
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required

# Create your views here.

from django.http import HttpResponse


def index(request):

    evento = Evento.objects.all()

    return render(request, 'home.html', {'eventos': evento})


class ver_evento(generic.DetailView):
    model = Evento
    template_name = "eventos/ver-evento.html"

@staff_member_required
def eliminar_eventos(request, id):

    evento = Evento.objects.get(pk=id)

    evento.delete()

    return redirect('index')

@staff_member_required
def crear_evento(request):

    return render(request, 'eventos/crear-evento.html')

@staff_member_required
def guardar_evento(request):

    if request.method == 'POST':

        titulo = request.POST['titulo']
        # validaciones

        if titulo == '':
            data = "Debes introducir el título del evento"
            return render(request, "eventos/crear-evento.html", {'data' : data})
        try:
            imagen = request.FILES['imagen']
        except:
            imagen = ""         

        descripcion = request.POST['descripcion']

        evento = Evento(
            titulo=titulo,
            descripcion=descripcion,
            imagen=imagen,
        )

        evento.save()

        return redirect('index')

    else:
        return HttpResponse("No se ha podido crear")

eventos/templates/home.html
{% extends 'layout.html' %}
{% load static %}
{% block title %} RM|Home {% endblock %}
{% block content%}
<div class="reserva">
    {% if user.is_authenticated %}

    <a href={% url 'reservas' %}><button class="boton-reserva">Reservar</button></a>

    {% else %}

    <a href={% url 'reservas' %}><button class="boton-reserva">Reservar</button></a>

    {% endif %}
</div>
<br>

<div class="social">
    <a href="http://instagram.com" target="_blank"> <i class="bi bi-instagram"> &nbsp; </i></a> 
    <a href="http://twitter.com"><i class="bi bi-twitter"> &nbsp; </i></a> 
    <a href="http://facebook.com"><i class="bi bi-meta"> &nbsp; </i></a> 
</div>
<br>
<hr>
<br>

{% if user.is_authenticated %}

{% else %}

<div class="registro">

    <a href="{% url 'registro' %}"><button>Registrarse</button></a>
    <a href="{% url 'login' %}"><button>Log in</button></a>

</div>


{% endif %}
<br/>
<br/>

<div class="imagen-home">
<img src="../static/images/cocktails.gif" alt="" class="img-home">
</div>

<br/>
<br/>

<h2>Eventos <i class='bx bx-down-arrow-alt bx-fade-down bx-flip-horizontal' ></i></h2>

<p>Aqui se publicaran eventos y ofertas</p>

{% if perms.reservas.add_evento %}
<div class="crear-eventos">
    <a href="{% url 'crear-evento' %}"><button>Crear Eventos</button></a>
    <hr>
</div>
{% endif %}
<div class="contenedor-eventos">
    {% if eventos %}
    {% for evento in eventos %}
    <div class="ofertas">
        <a href="{% url 'ver-evento' evento.id %}">


            <img class="img-evento" src="{% static 'images/' %}{{evento.imagen}}" alt="">
            <h2> {{evento.titulo}} </h2>

            {% if perms.reservas.delete_evento %}
            <a href="{% url 'eliminar-evento' evento.id %} ">Eliminar</a>
            {% endif %}
        </a>
    </div>
    {% endfor %}
    {% endif %}

</div>

{% endblock %}