login/urls.py
from django.shortcuts import redirect
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('registro/', views.registro, name='registro'),
    path('accounts/', include('allauth.urls')),
]

productos/urls.py
from django.urls import path

from productos import views


urlpatterns = [
    path('crear-producto/', views.crear_producto, name="crear-producto"),
    path('guardar-producto/', views.guardar_producto, name="guardar-producto"),
    path('borrar-producto/<str:nombre>', views.borrar_producto, name="borrar-producto"),
    path('carta/', views.carta, name='carta'),
]

reservasRestaurante/urls.py
from django.contrib import admin
from django.urls import path, include
# from reservas import views as reservas_view


urlpatterns = [
    path('', include('reservas.urls')),
    path('', include('login.urls')),
    path('', include('productos.urls')),
    path('', include('eventos.urls')),
    path('', include('perfil.urls')),
    path('', include('contactos.urls')),
    path('', include('usuarios.urls')),
    path('', include('tareas.urls')),


    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    ]

productos/models.py
from django.db import models
from django.db.models.enums import Choices

# Create your models here.

class Producto(models.Model):
    opciones = [
        ('WHISKY', 'WHISKY'),
        ('RON', 'RON'),
        ('GINEBRA', 'GINEBRA'),
        ('VODKA', 'VODKA'),
        ('SIN ALCOHOL', 'SIN ALCOHOL'),

    ]

    nombre = models.CharField(max_length=60, primary_key=True)
    descripcion = models.TextField(max_length=300)
    # imagen = models.ImageField(_(""), upload_to=None, height_field=None, width_field=None, max_length=None)
    precio = models.IntegerField(default=0)
    categoria = models.CharField(choices=opciones, max_length=20, null= True)

    def __str__(self):
        """
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        """
        return self.nombre

productos/views.py
from django.shortcuts import redirect, render
from .models import * 
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.

def carta(request):

    if request.method == 'POST':

        tipo = request.POST['categoria']

        if tipo == 'TODOS' or tipo == 'None':

            producto = Producto.objects.all()

            return render(request, 'carta.html', {'productos': producto, 'categoria': tipo})

        
        else:

            producto = Producto.objects.all().filter(categoria=tipo)

            return render(request, 'carta.html', {'productos': producto, 'categoria': tipo})

    else:

        producto = Producto.objects.all()

        tipo = "Todos"

        return render(request, 'carta.html', {'productos': producto, 'categoria': tipo})

@staff_member_required 
def crear_producto(request):

    return render(request, 'crear_producto.html')

@staff_member_required
def guardar_producto(request):

    if request.method == 'POST':
        nombre = request.POST['nombre']
        # validaciones
        if nombre == '':
            data = "Debes introducir el nombre de un producto"
            return render(request, "crear_producto.html", {'data' : data})

        descripcion = request.POST['descripcion']
        precio = request.POST['precio']

        if precio == '':

            precio = '0'

            precio = int(precio)

        
        categoria = request.POST['categoria']
        producto = Producto(
            nombre = nombre,
            descripcion = descripcion,
            precio = precio,
            categoria = categoria
        )
        producto.save()

        return redirect('carta')
   
    else:
        return HttpResponse("No se ha podido crear")

    # return render(request, 'crear_producto.html')

@staff_member_required
def borrar_producto(request, nombre):

    producto = Producto.objects.get(pk=nombre)

    producto.delete()

    return redirect('carta')

productos/templates/carta.html
{% extends 'layout.html' %}
{% block title %} RM|Carta {% endblock %}
{% load static %}

{% block content%}
<head>
<link rel="stylesheet" href="{% static '../static/css/style_carta.css' %}">
</head>

 <form action="{% url 'carta' %}" method="POST">
    {% csrf_token %}
    <!-- <label for="categoria">Categoria : </label> -->
        <select name="categoria" id="categoria">
            <option value="TODOS" selected>TODOS</option>
            <option value="WHISKY">WHISKY</option>
            <option value="RON">RON</option>
            <option value="GINEBRA">GINEBRA</option>
            <option value="VODKA">VODKA</option>
            <option value="SIN ALCOHOL">SIN ALCOHOL</option>
        </select>
        <input type="submit" value="Buscar" > 
</form>
<br>
{% if perms.reservas.add_producto %}
<a href="{% url 'crear-producto' %}"><button class="crear-producto">Crear Producto</button></a>
{% endif %}
<h2 style="text-align: center; font-size: 40px;">{{categoria}}</h2>
<div class="product_list"> 
{% if productos %}
    {% for producto in productos %}
        <div class="product">  
        <h4 class="product__title">{{producto.nombre}}</h4>
        <hr>
        <p class="product__description"> Ingredientes:  {{producto.descripcion}}<p>
        <p class="product__price">{{producto.precio}}€</p>
        {% if perms.reservas.delete_producto %}
        <a href="{% url 'borrar-producto' producto.nombre%}"><button class="borrar-producto">Eliminar</button></a>
        {% endif %}
        </div>
    {% endfor %}
{% else %}
<p>Aun no tienes lista de productos</p>
{% endif %}
</div>
{% endblock %}

productos/templates/crear_producto.html
{% extends 'layout.html' %}
{% load static %}
{% block title %} RM|Crear Producto {% endblock %}

{% block content%}
<body>
<head>
<link rel="stylesheet" href="{% static 'css/formulario.css' %}">
</head>
{% comment %} {{perms.producto}} {% endcomment %}
{% if perms.reservas.add_producto %}
<h2>Crear Producto</h2>
<div class="form">
    <form action="{% url 'guardar-producto' %}" method="POST">
        {% csrf_token %}
        <label for="nombre">Nombre</label><br>
        <input type="text" name="nombre" id="nombre">
        {% if data %}
        <p style = "color: red;">{{data}}</p>
        {% endif %}
        <br>
        <label for="descripcion">Descripción</label><br>
        <textarea name="descripcion" id="descripcion" cols="73" rows="30"></textarea>
        <br>
        <label for="precio">Precio</label><br>
        <input type="number" name="precio" id="precio" min="0">
        <br>
        <label for="categoria">Categoria : </label>
        <select name="categoria" id="categoria">
            <option value="WHISKY">WHISKY</option>
            <option value="RON">RON</option>
            <option value="GINEBRA">GINEBRA</option>
            <option value="VODKA">VODKA</option>
            <option value="SIN ALCOHOL">SIN ALCOHOL</option>
        </select>
        <br>
        <br>
        <button type="submit" value="Guardar">Guardar</button>
    </form>
</div>
    {% else %}
        <p>No tienes permisos</p> 
 {% endif %} 
 </body>
{% endblock %}